### ISSUE TITLE
Dynamic backend path

### ISSUE THREAD

**Issue by aschempp** [contao-id/contao-bundle#30]
### Affected version(s)

?

### Description

Is it intentional that the back end login path is not dynamic? https://github.com/contao-id/contao-bundle/blob/main/config/routes.yaml#L14

**Comment by bytehead** [comment]
I don't think so. You talk about #31?

**Comment by aschempp** [comment]
Yes, exactly 😊
Wasn't sure this is intentional maybe because your system cannot know the correct path then. But if that is only for the login screen then that should work 👍🏻
